[project]
name = "production-ready-template"
version = "0.1.0"
description = "A production-ready Python API template with FastAPI, Postgres, Docker & Nginx"
authors = [
    {name = "Subhan Javaid"}
]
requires-python = "^3.11"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn[standard] (>=0.52.4,<0.53.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
